name: Sign_sojiang

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'
jobs:
  soujiang:
    runs-on: windows-2022
    
    steps:
      - name: 'Sign_sojiang ....' 
        run: |
          # cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/start.bat
          # cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/python_install.bat
          # cmd /c start.bat
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/Sign_sojiang.py
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/chromedriver.exe
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/AutoVerify.crx
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/requirements.txt
          cmd /c pip install -r requirements.txt
          cmd /c python Sign_sojiang.py "user" "password"
          # cmd /c python Sign_sojiang.py "user1 user2" "password1 password2"
          
