name: ADS

on:
  workflow_dispatch:
  schedule:
    - cron: '33 */3 * * *'
jobs:
  ADS:
    runs-on: windows-2022
    
    steps:
      - name: 'ADS' 
        run: |
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/Sign_google.py
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/chromedriver.exe
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/requirements.txt
          cmd /c pip install -r requirements.txt
          cmd /c python Sign_google.py 'https://www.spiritlhl.top/'
